import assets from "../assets/assets";

export const bookings = [
  {
    id: 1,
    holder: "Angelina Marcus",
    date: "Jan. 31st, 2024",
    day: "Monday",
    type: "New Booking",
    field: "North Field",
    time: "9-10pm",
    status: "Pending",
  },

  {
    id: 2,
    holder: "Ronald Regan",
    date: "Jan. 31st, 2024",
    day: "Monday",
    type: "Recurring Booking",
    field: "North Field",
    time: "9-10pm",
    status: "Client Cancellation",
  },
  {
    id: 3,
    holder: "Rockets vs Orlandians",
    date: "Jan. 31st, 2024",
    day: "Monday",
    type: "League: Semi-Finals",
    field: "Jr Field",
    time: "9-10pm",
    status: "Fulfilled",
  },
  {
    id: 4,
    holder: "Free Play",
    date: "Jan. 31st, 2024",
    day: "Monday",
    type: "Pickup: Free Play",
    field: "East Field",
    time: "9-10pm",
    status: "Fulfilled",
  },
  {
    id: 5,
    holder: "Little Angels",
    date: "Jan. 31st, 2024",
    day: "Monday",
    type: "Academy",
    field: "South Field",
    time: "9-10pm",
    status: "Removed",
  },
  {
    id: 6,
    holder: "Ashton Brown",
    date: "Jan. 31st, 2024",
    day: "Monday",
    type: "Recurring Booking",
    field: "South Field",
    time: "9-10pm",
    status: "Admin Cancellation",
  },
];

export const sales = [
  {
    id: 1,
    holder: "Angelina Marcus",
    date: "Jan. 31st, 2024",
    day: "Monday",
    type: "New Booking",
    field: "North Field",
    time: "9-10pm",
    payment: "$80",
  },

  {
    id: 2,
    holder: "Ronald Regan",
    date: "Jan. 31st, 2024",
    day: "Monday",
    type: "League",
    field: "North Field",
    time: "9-10pm",
    payment: "Error",
  },
  {
    id: 3,
    holder: "Angelina Marcus",
    date: "Jan. 31st, 2024",
    day: "Monday",
    type: "League",
    field: "North Field",
    time: "9-10pm",
    payment: "$80",
  },

  {
    id: 4,
    holder: "Ronald Regan",
    date: "Jan. 31st, 2024",
    day: "Monday",
    type: "Recurring Booking",
    field: "North Field",
    time: "9-10pm",
    payment: "Error",
  },
  {
    id: 5,
    holder: "Angelina Marcus",
    date: "Jan. 31st, 2024",
    day: "Monday",
    type: "New Booking",
    field: "North Field",
    time: "9-10pm",
    payment: "$80",
  },

  {
    id: 6,
    holder: "Ronald Regan",
    date: "Jan. 31st, 2024",
    day: "Monday",
    type: "Recurring Booking",
    field: "North Field",
    time: "9-10pm",
    payment: "Error",
  },
  {
    id: 7,
    holder: "Ronald Regan",
    date: "Jan. 31st, 2024",
    day: "Monday",
    type: "League",
    field: "North Field",
    time: "9-10pm",
    payment: "Error",
  },
];
export const paymentDetails = [
  { id: 1, user: "Tiger T46" },
  {
    id: 2,
    user: "Ryan Adams ID99",
    transactionId: "12871623",
    salesTax: "$0.65",
    playerTotal: "$8",
    credit: "($20 % off)",
  },
  {
    id: 3,
    user: "Ryan Adams ID99",
    transactionId: "12871623",
    salesTax: "$0.65",
    playerTotal: "$8",
    credit: "($20 % off)",
  },
  {
    id: 4,
    user: "Ryan Adams ID99",
    transactionId: "12871623",
    salesTax: "$0.65",
    playerTotal: "$8",
    credit: "($20 % off)",
  },
  {
    id: 5,
    user: "Ryan Adams ID99",
    transactionId: "12871623",
    salesTax: "$0.65",
    playerTotal: "$8",
    credit: "($20 % off)",
  },
  {
    id: 6,
    user: "Ryan Adams ID99",
    transactionId: "12871623",
    salesTax: "$0.65",
    playerTotal: "$8",
    credit: "($20 % off)",
  },

  { id: 7, user: "FC City T55" },
  {
    id: 8,
    user: "Ryan Adams ID99",
    transactionId: "12871623",
    salesTax: "$0.65",
    playerTotal: "$8",
    credit: "($20 % off)",
  },
  {
    id: 9,
    user: "Ryan Adams ID99",
    transactionId: "12871623",
    salesTax: "$0.65",
    playerTotal: "$8",
    credit: "($20 % off)",
  },
  {
    id: 10,
    user: "Ryan Adams ID99",
    transactionId: "12871623",
    salesTax: "$0.65",
    playerTotal: "$8",
    credit: "($20 % off)",
  },
  {
    id: 11,
    user: "Ryan Adams ID99",
    transactionId: "12871623",
    salesTax: "$0.65",
    playerTotal: "$8",
    credit: "($20 % off)",
  },
  {
    id: 12,
    user: "Ryan Adams ID99",
    transactionId: "12871623",
    salesTax: "$0.65",
    playerTotal: "$8",
    credit: "($20 % off)",
  },
];

export const paymentRecurDetails = [
  { id: 1, user: "Tiger T46" },
  {
    id: 2,
    user: "Ryan Adams ID99",
    transactionId: "",
    salesTax: "$0",
    playerTotal: "$0",
  },
  {
    id: 3,
    user: "Ryan Adams ID99",
    transactionId: "",
    salesTax: "$0",
    playerTotal: "$0",
  },
  {
    id: 4,
    user: "Ryan Adams ID99",
    transactionId: "",
    salesTax: "$0",
    playerTotal: "$0",
  },
  {
    id: 5,
    user: "Ryan Adams ID99",
    transactionId: "",
    salesTax: "$0",
    playerTotal: "$0",
  },
  {
    id: 6,
    user: "Ryan Adams ID99",
    transactionId: "",
    salesTax: "$0",
    playerTotal: "$0",
  },

  { id: 7, user: "FC City T55" },
  {
    id: 8,
    user: "Ryan Adams ID99",
    transactionId: "",
    salesTax: "$0",
    playerTotal: "$0",
  },
  {
    id: 9,
    user: "Ryan Adams ID99",
    transactionId: "",
    salesTax: "$0",
    playerTotal: "$0",
  },
  {
    id: 10,
    user: "Ryan Adams ID99",
    transactionId: "",
    salesTax: "$0",
    playerTotal: "$0",
  },
  {
    id: 11,
    user: "Ryan Adams ID99",
    transactionId: "",
    salesTax: "$0",
    playerTotal: "$0",
  },
  {
    id: 12,
    user: "Ryan Adams ID99",
    transactionId: "",
    salesTax: "$0",
    playerTotal: "$0",
  },
];

export const usersDetails = [
  {
    id: 1,
    client: "Angelina Marcus",
    firstvisit: "1 yr ago",
    lastvisit: "3 m ago",
    visits: "45",
    noshows: "02",
    cancel: "12",
    yourcancel: "03",
    revenue: "435.678",
  },
  {
    id: 2,
    client: "Ronald Regan",
    firstvisit: "1 yr ago",
    lastvisit: "3 m ago",
    visits: "45",
    noshows: "02",
    cancel: "12",
    yourcancel: "03",
    revenue: "435.678",
  },
  {
    id: 3,
    client: "Juan Pedro",
    firstvisit: "1 yr ago",
    lastvisit: "3 m ago",
    visits: "45",
    noshows: "02",
    cancel: "12",
    yourcancel: "03",
    revenue: "435.678",
  },
  {
    id: 4,
    client: "Syed Moazzam",
    firstvisit: "1 yr ago",
    lastvisit: "3 m ago",
    visits: "45",
    noshows: "02",
    cancel: "12",
    yourcancel: "03",
    revenue: "435.678",
  },
  {
    id: 5,
    client: "Lewis Clarke",
    firstvisit: "1 yr ago",
    lastvisit: "3 m ago",
    visits: "45",
    noshows: "02",
    cancel: "12",
    yourcancel: "03",
    revenue: "435.678",
  },
  {
    id: 6,
    client: "Ashton Brown",
    firstvisit: "1 yr ago",
    lastvisit: "3 m ago",
    visits: "45",
    noshows: "02",
    cancel: "12",
    yourcancel: "03",
    revenue: "435.678",
  },
  {
    id: 7,
    client: "Lewis Hanz",
    firstvisit: "1 yr ago",
    lastvisit: "3 m ago",
    visits: "45",
    noshows: "02",
    cancel: "12",
    yourcancel: "03",
    revenue: "435.678",
  },
];
export const holderDetails = [
  {
    id: 1,
    client: "Angelina Marcus",
    email: "angelina_marcus018@gmail.com",
    phone: "+1(985) 8690-2225",
    balance: "$17.89",
  },
  {
    id: 2,
    client: "Ronald Regan",
    email: "angelina_marcus018@gmail.com",
    phone: "+1(985) 8690-2225",
    balance: "$17.89",
  },
  {
    id: 3,
    client: "Juan Pedro",
    email: "angelina_marcus018@gmail.com",
    phone: "+1(985) 8690-2225",
    balance: "$17.89",
  },
  {
    id: 4,
    client: "Syed Moazzam",
    email: "angelina_marcus018@gmail.com",
    phone: "+1(985) 8690-2225",
    balance: "$17.89",
  },
  {
    id: 5,
    client: "Ibrahim Sheikh",
    email: "angelina_marcus018@gmail.com",
    phone: "+1(985) 8690-2225",
    balance: "$17.89",
  },
  {
    id: 6,
    client: "Ashton Brown",
    email: "angelina_marcus018@gmail.com",
    phone: "+1(985) 8690-2225",
    balance: "$17.89",
  },
  {
    id: 7,
    client: "Lewis Hanz",
    email: "angelina_marcus018@gmail.com",
    phone: "+1(985) 8690-2225",
    balance: "$17.89",
  },
];

export const eventData = [
  {
    eventName: "Select League, Co ed, Division 1 (Season 1, 2024)",
    type: "League + KO",
    started: "Mar. 3, 2024",
    progress: 60,
    totalTeams: 16,
    numTeams: 16,
    players: 160,
    freeAgents: 14,
    avgAge: 22,
    malePrcnt: 78,
    femalePrcnt: 22,
    avgPlyrPayment: 100,
    revenue: 300.23,
    status: "Active", // Added status field
  },
  {
    eventName: "Toddler's League",
    type: "League",
    started: "Mar. 3, 2024",
    ended: "Mar. 22, 2024",
    totalTeams: 12,
    numTeams: 12,
    players: 112,
    freeAgents: 10,
    avgAge: 12,
    malePrcnt: 50,
    femalePrcnt: 50,
    avgPlyrPayment: 25,
    revenue: 34013.23,
    status: "Completed", // Added status field
  },
  {
    eventName: "USA Amateur's Cup",
    type: "League",
    started: "Mar. 3, 2024",
    progress: 0,
    totalTeams: 10,
    numTeams: 1,
    players: 7,
    freeAgents: 0,
    avgAge: 21,
    malePrcnt: 96,
    femalePrcnt: 4,
    avgPlyrPayment: 120,
    revenue: 0,
    status: "Active", // Added status field
  },
];
export const teamsData = [
  {
    icon: assets.team1, // Replace with actual image path
    name: "The Tigers",
    paymentStatus: "confirmed",
    leagueParticipation: 4,
  },
  {
    icon: assets.team2, // Replace with actual image path
    name: "Arsenal Gunners",
    paymentStatus: "pending",
    leagueParticipation: 2,
  },
  {
    icon: assets.team3, // Replace with actual image path
    name: "FC Hanover",
    paymentStatus: "confirmed",
    leagueParticipation: 5,
  },
  {
    icon: assets.team4, // Replace with actual image path
    name: "FC Fulham",
    paymentStatus: "pending",
    leagueParticipation: 3,
  },
  {
    icon: assets.team5, // Replace with actual image path
    name: "Atlanta FC",
    paymentStatus: "confirmed",
    leagueParticipation: 1,
  },
  {
    icon: assets.team6, // Replace with actual image path
    name: "Strikers",
    paymentStatus: "confirmed",
    leagueParticipation: 1,
  },
  {
    icon: assets.team7, // Replace with actual image path
    name: "USA Soccer FC",
    paymentStatus: "confirmed",
    leagueParticipation: 1,
  },
];

export const playersData = [
  {
    name: "Justin Mcnab",
    img: assets.player1,
    isAdmin: true,
    isPro: true,
    isFreeAgent: false,
  },
  {
    name: "Jane Smith",
    img: assets.player2,
    isAdmin: false,
    isPro: false,
    isFreeAgent: true,
  },
  {
    name: "Ibrahim Sheikh",
    img: assets.player3,
    isAdmin: false,
    isPro: false,
    isFreeAgent: false,
  },
  {
    name: "John Doe",
    img: assets.player4,
    isAdmin: false,
    isPro: true,
    isFreeAgent: false,
  },

  // Add more player objects as needed
];
export const freeAgents = [
  {
    name: "John Doe",
    img: assets.club,
    isPro: true,
    isFreeAgent: true,
  },
  {
    name: "Jane Smith",
    img: assets.club,
    isPro: false,
    isFreeAgent: true,
  },
  {
    name: "Jane Smith",
    img: assets.club,
    isPro: false,
    isFreeAgent: true,
  },
  {
    name: "Justin McNab",
    img: assets.club,
    isPro: true,
    isFreeAgent: true,
  },
  {
    name: "Ali Lal Din",
    img: assets.club,
    isPro: true,
    isFreeAgent: true,
  },
  {
    name: "Ibrahim Sheikh",
    img: assets.club,
    isPro: true,
    isFreeAgent: true,
  },
  // Add more player objects as needed
];
